"use client";

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export function FAQSection() {
    return (
        <section className="py-16 lg:py-24">
            <div className="mx-auto max-w-3xl px-6 lg:px-8">
                <div className="text-center mb-12">
                    <h2 className="font-display text-3xl font-bold">Frequently Asked Questions</h2>
                </div>
                <Accordion type="single" collapsible className="w-full">
                    <AccordionItem value="item-1">
                        <AccordionTrigger>How do I receive my prompts?</AccordionTrigger>
                        <AccordionContent>
                            Immediately after purchase, you will receive a secure download link via email. You can also access your purchases anytime from your account dashboard.
                        </AccordionContent>
                    </AccordionItem>
                    <AccordionItem value="item-2">
                        <AccordionTrigger>Is this a recurring subscription?</AccordionTrigger>
                        <AccordionContent>
                            No. All our prompt packs are one-time purchases. You pay once and own it forever, including any future updates to that specific pack.
                        </AccordionContent>
                    </AccordionItem>
                    <AccordionItem value="item-3">
                        <AccordionTrigger>Do you offer refunds?</AccordionTrigger>
                        <AccordionContent>
                            Due to the digital nature of our products, we generally do not offer refunds. However, if you are unsatisfied with your purchase, please contact our support team and we will do our best to resolve the issue.
                        </AccordionContent>
                    </AccordionItem>
                    <AccordionItem value="item-4">
                        <AccordionTrigger>Can I use these prompts for commercial projects?</AccordionTrigger>
                        <AccordionContent>
                            Yes! You are free to use the outputs generated by our prompts for any commercial or personal projects. You cannot, however, resell the prompt packs themselves.
                        </AccordionContent>
                    </AccordionItem>
                </Accordion>
            </div>
        </section>
    );
}
